language: node_js
node_js:
  - "6"
  - "8"
brancher:
  only:
    - "dev"
    - "master"
install:
  - "npm install"
  - "npm install -g codecov"
script:
  - "npm run cover"
  - "codecov"
CODECOV_TOKEN: "bea9d7cb-c158-4207-abe1-7a16508db45e"